apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kabal-frontend
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 3
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no

  accessPolicy:
    inbound:
      rules:
        - application: klage-oppgave-e2e
    outbound:
      rules:
        - application: klage-redis-fe
        - application: kabal-api
      external:
        - host: login.microsoftonline.com
        - host: kabal-api.dev.nav.no
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  envFrom:
    - secret: klagesessionkey
